### ISSUE TITLE
Installing via pip

### ISSUE THREAD

**Issue by cole-jacobs** [sbdchd/django-types#1]
Hey! Looks like a great project . My intention is to take advantage of these stubs with pyright, but attempting to install via pip failed with the following error messages:

`ERROR: Could not find a version that satisfies the requirement django-types`
`ERROR: No matching distribution found for djang-types`

Maybe I overlooked it, but I didn't notice any version requirements. The project I'm working on uses python 3.6.12 and Django 2.2.17. Are these stubs compatible?

As an aside... once this package is successfully installed, is it as simple as providing the package directory to pyright's stub path configuration?

**Comment by sbdchd** [comment]
Oh sorry, somehow I missed this issue

if you install a specific version does it work?

I think both of those versions should work and pyright should be able to find these stubs by default since it looks for `-stub` packages in the `.venv`

**Comment by sbdchd** [comment]
Should be fixed in the latest version `0.4.1`, please reopen if it isn't

**Comment by cole-jacobs** [comment]
Thanks for taking care of this for me!
