### ISSUE TITLE
`null` on Foreign* is typed wrong

### ISSUE THREAD

**Issue by antifuchs** [sbdchd/django-types#101]
The `null` field on ForeignKey and ForeignObject should accept `bool` values (so you can set `null=True` on fields without type errors. Currently, it only [accepts `Literal[False]`](https://github.com/sbdchd/django-types/blob/55ad0d13904278ae24d488c1a68b6a5c119cab63/django-stubs/db/models/fields/related.pyi#L197), so you can turn nullability off explicitly (which is the default anyway), but not on.

The django-stubs repo has [the correct type signature for this property](https://github.com/typeddjango/django-stubs/blob/cf31c1de7b9c0ac4bc3b18edb80b07bc21e95385/django-stubs/db/models/fields/related.pyi#L109), and doesn't seem to have had the problem previously... is the fix here just to do whatever django-stubs does?

**Comment by benesch** [comment]
> is the fix here just to do whatever django-stubs does?

Almost surely, and @sbdchd has been wonderful about merging my PRs in the past, so I'd say send it up!

**Comment by bellini666** [comment]
@antifuchs it is actually typed correctly, the `__new__` method is being overloaded.

If you are typing the foreignkey by yourself you may be falling into the same trap as [this issue](https://github.com/sbdchd/django-types/issues/85). Take a look at my comments there (specially the first reply) that might solve your issue.

**Comment by antifuchs** [comment]
Agh, that makes sense - I missed that the field is explicitly typed to be non-optional. Changing that does fix the type error (it's just a bit of a confusing type error from pyrite).
