### ISSUE TITLE
False negative due to removed `db_table` argument on `ManyToManyField`

### ISSUE THREAD

**Issue by vst** [sbdchd/django-types#104]
Seems like `db_table` has been removed in PR #97.

https://github.com/sbdchd/django-types/pull/97/files#diff-1b81097ad0483c0e4587c2c3f8902aec74c6fa470aedf239372e09eb632162f0L468-L468

**Comment by sbdchd** [comment]
Ah so you're passing `db_table` and getting an error when you shouldn't?

**Comment by vst** [comment]
Yep. That's correct. Seems like we should add the `db_table` argument back to `ManyToManyField`.

Indeed, this is happening for the second time :). See https://github.com/sbdchd/django-types/pull/80.
