### ISSUE TITLE
pyright can't infer model field types

### ISSUE THREAD

**Issue by kylebebak** [sbdchd/django-types#12]
Hey @sbdchd , I'd also like to try using `pyright` instead of `mypy` on a Django codebase, and you're the only person I've found that mentions trying to use `pyright` with the type stubs from `django-stubs`!

**I'm on Django 3.1.6, with pyright 1.1.122**.

Just out of curiosity, have you been able to get `pyright` to work for inferring model field types on models? Here are some images of `pyright` doing type inference in my text editor:

<img width="355" alt="Screen Shot 2021-03-20 at 2 01 14 PM" src="https://user-images.githubusercontent.com/1524088/111884122-0ad02180-8985-11eb-81d6-d6302e55c7b0.png">

<img width="349" alt="Screen Shot 2021-03-20 at 2 01 26 PM" src="https://user-images.githubusercontent.com/1524088/111884130-2cc9a400-8985-11eb-83ef-510e708e7657.png">

I instantiate a `prod` from a `Product`, which has a `name` field that's a `CharField`. `pyright` knows `prod` is a `Product`, but it thinks `prod.name` has a type of `Unknown`

Also, the trick you mentioned with `objects = Manager["Product"]()` doesn't seem to work -- `product` has a type of `Any | None`

<img width="326" alt="Screen Shot 2021-03-20 at 2 08 34 PM" src="https://user-images.githubusercontent.com/1524088/111884215-c6915100-8985-11eb-9f6c-e7729dc88b5e.png">

Also looking into this here: https://github.com/typeddjango/django-stubs/issues/579

**Comment by sbdchd** [comment]
Which version of `django-types` are you using?

In the test suite I the types are working for me:

![Screen Shot 2021-03-20 at 6 02 56 PM](https://user-images.githubusercontent.com/7340772/111886761-9f974700-89a6-11eb-8af5-060dcb002e42.png)

**Comment by kylebebak** [comment]
Nvm @sbdchd , I take it all back.

I had copied the stubs from `django-stubs` into a `typings` dir for my project, I figured they would just work. After I copied the stubs from your repo instead everything worked!

The work you've done is **awesome**. It would be even more awesome if the stubs in `django-stubs` worked with `pyright` without having to change them, because unless otherwise this repo won't get improvements from `django-stubs` unless someone is pulling them in continually.

I'm going to close this =)

**Comment by sbdchd** [comment]
Glad the stubs are working!

Refactoring `django-stubs` to work with `pyright` (and `mypy` without the `django-stubs` plugin) was a decent amount of work mostly consisting of deleting `mypy` plugin specific type annotations and fixing various `@overload`s.

I think `django-stubs` might be able to support both `mypy` and other type checkers, but it would require lots of changes.

**Comment by kylebebak** [comment]
Thanks for explaining this. I'm going to point the `django-stubs` guys to this repo just so they know it's possible to use their stubs with other type checkers, or with `mypy` without using the plugin.
