### ISSUE TITLE
TypeError: type 'CharField' is not subscriptable

### ISSUE THREAD

**Issue by adonig** [sbdchd/django-types#150]
I was trying to reproduce the setup from [a DjangoCon 2022 talk](https://www.youtube.com/watch?v=Lz4I7rFmFdY) about type checking Django with pyright and django-types.

At around minute [26:16](https://youtu.be/Lz4I7rFmFdY?t=1578) you can see some code where a CharField gets subscripted with a literal string type. 

For some strange reason that code causes a TypeError when I run `python manage.py runserver` complaining that the type CharField is not subscriptable.

I thought, maybe I have to install django-types directly from GitHub instead of pip but it didn't work either. Does anyone maybe have a hint what I have to do to make it work?

**Comment by sbdchd** [comment]
are you monkey patching Django to allow for the indexing?

```python
# in settings.py
from django.db.models import ForeignKey
from django.db.models.manager import BaseManager
from django.db.models.query import QuerySet

# NOTE: there are probably other items you'll need to monkey patch depending on
# your version.
for cls in [QuerySet, BaseManager, ForeignKey]:
    cls.__class_getitem__ = classmethod(lambda cls, *args, **kwargs: cls)  # type: ignore [attr-defined]
```

**Comment by adonig** [comment]
@sbdchd I thought it's not necessary because I run Django 4.1.5 and the documentation says:

> You'll need to monkey patch Django's QuerySet, Manager (**not needed for Django 3.1+**) and ForeignKey (**not needed for Django 4.1+**) classes so we can index into them with a generic argument. Add this to your settings.py:

Just to make sure I put the monkeypatch in my settings.py and sadly the error doesn't go away:

![image](https://user-images.githubusercontent.com/900404/216845964-e2017817-2ac0-4c79-a386-1130f0117faf.png)

**Comment by sbdchd** [comment]
Oh I didn't have all the classes in the snippet, if you include CharField (or it's parent class maybe?) does it work?

**Comment by adonig** [comment]
Yes, that works. Thank you. Now I get what that note in the monkey-patch snippet means.

> NOTE: there are probably other items you'll need to monkey patch depending on your version

Is there a list of things that generally make sense to get monkey-patched?

**Comment by sbdchd** [comment]
I basically only monkey patch when something explodes at runtime

I think you can avoid it for most things, but the ORM needs a decent amount of it unfortunately
