### ISSUE TITLE
Django-ninjas urls have the wrong shape for django.urls.path

### ISSUE THREAD

**Issue by bobthemighty** [sbdchd/django-types#173]
The signature of `path` in the stubs expects a `view` parameter of type `List[Union[URLResolver, str]]`

But Django-ninjas gives 

```
Tuple[List[Union[URLResolver, URLPattern]], str, str]:
```

I'm happy to open a PR to fix the discrepancy, but I'm frankly lost trying to understand what the type here _should_ be.

**Comment by sbdchd** [comment]
Hmm I'm not sure what the usage is supposed to look like but I imagine Django-ninja's is probably correct

There are some existing overloads:

https://github.com/sbdchd/django-types/blob/d97beb9a422a304581fcb09619f12a66c857cb47/django-stubs/urls/conf.pyi#L40

**Comment by bobthemighty** [comment]
Do you want me to just dump in another overload to satisfy this case? I could spend some time trying to work out what the heck that function actually _does_ but I'm not sure I have the context to do a good job.
