### ISSUE TITLE
Classmethod returning `Self` makes Pylance raise `reportReturnType`

### ISSUE THREAD

**Issue by simensol** [sbdchd/django-types#226]
When my custom managers went from untyped:

```py
objects  = GroupManager()
```

to typed:

```py
objects: ClassVar[GroupManager] = GroupManager()
```

classmethods returning `Self`, e.g.:

```py
@classmethod
def create(
    cls,
    name: str
) -> Self:
    return cls.objects.create(
        name=name,
    )
```

started to raise the following linting error:

```bash
Expression of type "Group" cannot be assigned to return type "Self@Group"
  Type "Group" cannot be assigned to type "Self@Group" Pylance(reportReturnType)
```

I fixed this by returning `"Group"` instead:

```py
@classmethod
def create(
    cls,
    name: str
) -> "Group":
    return cls.objects.create(
        name=name,
    )
```

However, according to [PEP 673](https://peps.python.org/pep-0673/#use-in-classmethod-signatures), a classmethod should be able to return `Self`.

**Comment by sbdchd** [comment]
Hmm is this a pyright issue?

**Comment by simensol** [comment]
If you think so @sbdchd, I can raise the issue in the Pyright repro?

**Comment by simensol** [comment]
Correct types solved the issue. See https://github.com/microsoft/pyright/issues/7251#issuecomment-1940625332 for solution.
