### ISSUE TITLE
Allow CharField to define a generic enum type

### ISSUE THREAD

**Issue by bellini666** [sbdchd/django-types#34]
It would be nice to have support for this: https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types

Maybe something like this:

```python
class SomeEnum(models.TextFields):
    FOO = "foo"
    BAR = "bar"

some_enum_field = models.CharField[SomeEnum](  # note the [SomeEnum] generic here
    choices=SomeEnum.choices,
    default=SomeEnum.FOO,
)
```

This way the typing would know that the field reads and writes that exact enum type and not a str.

**Comment by sbdchd** [comment]
Interesting, playing around with it a bit, and it seems like the Django API makes it a little tricky to do this, ideally we'd pass in `SomeEnum` as a param, and then we could use that for the `@overload`.

Something like 



```python
class FooModel(models.Model):

    class BarEnum(models.TextChoices):
        FOO = "foo"
        BAR = "bar"

    some_enum_field = models.CharField(
       # something like this would allow for an @overload
        enum=BarEnum,
        default=BarEnum.FOO,
    )
```

**Comment by sbdchd** [comment]
Also by 

> reads and writes that exact enum type and not a str

Do you mean the __set__ and __get__ would be `Literal["foo", "bar"]`?

**Comment by bellini666** [comment]
Hey @sbdchd ,

I always defined enums the old way without the `models.TextChoices`, and after seeing its existence yesterday I theocrafted that it would *get* and *set* the enum itself, but I just noticed that even though the  *set* accepts the enum, the *get* reads it as a string, which is said :(

Having said that, allowing to declare the `CharField` that it *get*/*set* `Literal["foo", "bar"]` would be awesome! The same applies to `IntegerField` with choices defined.
