### ISSUE TITLE
Why is ManyToManyField not generic?

### ISSUE THREAD

**Issue by ylilarry** [sbdchd/django-types#51]
Is there a reason for the ManyToManyField not be able to be defined as this?

```
class ManyToManyField(Generic[_M], RelatedField[Sequence[_M], RelatedManager[_M]]):
```

**Comment by ylilarry** [comment]
See #52

**Comment by sbdchd** [comment]
yeah that looks good, I don't use the field type much so it hasn't gotten much attention

There are a few edge cases with the `ManyToManyField` to be mindful of:

```python
from django.db import models

class Person(models.Model):
    friends = models.ManyToManyField("self")
```

https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.ManyToManyField
