### ISSUE TITLE
psycopg2-stubs shadow typeshed stubs

### ISSUE THREAD

**Issue by ewjoachim** [sbdchd/django-types#74]
It took me a while to find that it was this package that caused my issue.

There are more complete stubs of psycopg2 in typeshed: https://github.com/python/typeshed/tree/master/stubs/psycopg2 which are automatically released as a PEP 561 package at https://pypi.org/project/types-psycopg2/

Installing both ``types-psycopg2`` and ``django-types`` results in one unpredictibly shadowing the other, so mypy sometimes works and sometimes doesn't. Would you accept a PR that would remove psycopg2 types defined here and rely on the typeshed ones instead ?

**Comment by sbdchd** [comment]
Yeah that works for me, the only downside I see is the types in the type shed aren't as fleshed out

**Comment by ewjoachim** [comment]
I don't know if the stubs in typeshed are less complete.
What I can say is that `psycopg2.extra.Json` exist in typeshed and in `psycopg2` but not in here. So does `psycopg2.pool`. 

The people over at typeshed are quick to merge PRs, so it shouldn't be too hard to add missing stuff there.

**Comment by sbdchd** [comment]
Yeah I think the type shed will have more stubs since it was created using stub gen, but right now they're a little thin on the type annotations

for instance `parse_dsn` is typed as `Any -> Any` and the connection cursor has an `__enter__` return type of `Any` which means if we use the cursor like:

```py
with connection.cursor() as conn:
    conn # this will be Any
```

**Comment by ewjoachim** [comment]
Looking at the stubs here, I'm seeing that `connection.cursor` would return a cursor instance whose `fetchone` type is a `Tuple`. But if you configured your connection's `cursor_factory` to use a DictCursor, then `fetchone` will return a `Dict`.  I know that it might not make a lot of sense in the context of Django, but this means we can have a lot of problems if the project uses psycopg2 directly alongside with Django.
Also... How do we know it's psycopg2 and not, say, MariaDB or sqlite ?

**Comment by sbdchd** [comment]
Revisiting this, I think removing the psycopg2 types from this package and using the type shed ones is the way forward

**Comment by ewjoachim** [comment]
(had completely forgotten about this issue. Not sure I have a lot of time to make a PR)
